name = "dnd-cheatsheet-proxy"
main = "index.js"
compatibility_date = "2024-01-01"
account_id = "eaec893fc2ee46a2fdd1a9e9dfac5fe7"

[[kv_namespaces]]
binding = "SYNC"
id = "69dea3bde30d4d6e935e7c163666e386"
